/**
 * Type definition generated by {@link https://github.com/Guibi1/Maki Maki}.
 */
declare type MakiServerEndpoints = {
    "api": import("maki/server").MakiServerEndpoint<typeof import("./routes/api/server")>;
    "api/[id]": import("maki/server").MakiServerEndpoint<typeof import("./routes/api/[id]/server")>;
};
